2024-09-29 19:52:28,518 - INFO - Démarrage de l'exécution
2024-09-29 19:52:28,518 - INFO - Chargement du modèle depuis ../src/stylegan3-t-ffhq-1024x1024.pkl...
2024-09-29 19:52:37,381 - INFO - Modèle chargé avec succès.
2024-09-29 19:52:37,381 - INFO - ImageGenerator initialisé avec succès.
2024-09-29 19:52:37,382 - INFO - Chargement de l'image depuis : ../data/test_enfant.png
2024-09-29 19:52:37,429 - INFO - Image redimensionnée à 1024x1024.
2024-09-29 19:52:37,491 - INFO - Image transformée et prête pour la génération.
2024-09-29 19:52:42,545 - INFO - Optimisation à la résolution 64x64
2024-09-29 19:53:38,668 - INFO - Étape 0/5000 à 64x64, Perte totale: 0.3383486568927765
2024-09-29 19:53:38,793 - ERROR - Une erreur est survenue
2024-09-29 19:53:38,794 - ERROR - Détails de l'exception : 
Traceback (most recent call last):
  File "/notebooks/scripts/main.py", line 71, in main
    generator.project_with_progressive_growing()
  File "/notebooks/scripts/ImageGenerator.py", line 185, in project_with_progressive_growing
    total_loss.backward()
  File "/usr/local/lib/python3.11/dist-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/usr/local/lib/python3.11/dist-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.
